apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: componentlibrary-io
spec:
  secretName: componentlibrary-io-tls
  commonName: componentlibrary.io
  dnsNames:
  - componentlibrary.io
  - www.componentlibrary.io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
