apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: markweldonbrewer/cl-server
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: ds237989
            - name: MONGO_PORT
              value: '37989'
            - name: MONGO_USERNAME
              value: MWBrewer
            - name: MONGO_DB
              value: component-library
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongopassword
                  key: MONGO_PASSWORD
